### ISSUE TITLE
Rails Hello World

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/code-art-marketplace_rest-api_ruby_rails#1]
# Description

A Hello World REST API program in the [Rails](https://rubyonrails.org/) framework

# Tasks
- [ ] Setup initial Rails project
- [ ] Run project locally
- [ ] Code and run hello world endpoint
- [ ] Code and run an endpoint that is configured to return JSON
